openapi: 3.0.3
tags:
  - name: users
info:
  contact:
    name: Mr. Support
  description: My test API.
  title: nx-poc API
  version: "1.0"
servers:
  - url: http://localhost:3000
    description: local
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params-only
paths:
  /users/{id}:
    parameters:
      - schema:
          $ref: ./schemas/NanoID.yml
        name: id
        in: path
        required: true
        description: An existing user's ID.
    get:
      description: Get a user by ID.
      operationId: getUserById
      responses:
        "200":
          description: User found.
          content:
            application/json:
              schema:
                $ref: ./schemas/User.yml
              examples:
                Get User Alice Smith:
                  value:
                    created: "2020-01-01T12:00:00.000Z"
                    email: alice.smith@gmail.com
                    id: KavFhNwo9R7_tVno2vSbt
                    name: Alice Smith
        "404":
          description: User not found.
      tags: [users]
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: "{{integrationUri}}"
        credentials: "{{integrationCredentials}}"
        httpMethod: GET
        responses:
          2\\d{2}:
            statusCode: "200"
          default:
            statusCode: "400"
            responseTemplates:
              "application/json": "json 400 response template"
  /users:
    post:
      description: Create a new user.
      operationId: createUser
      responses:
        "200":
          description: User created.
          content:
            application/json:
              schema:
                $ref: ./schemas/User.yml
              examples:
                New User Alice Smith:
                  value:
                    created: "2020-01-01T12:00:00.000Z"
                    email: alice.smith@gmail.com
                    id: KavFhNwo9R7_tVno2vSbt
                    name: Alice Smith
        "400":
          description: Bad request.
        "409":
          description: Email already taken.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/CreateUser.yml
            examples:
              New User Alice Smith:
                value:
                  email: alice.smith@gmail.com
                  name: Alice Smith
      tags: [users]
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: "{{integrationUri}}"
        credentials: "{{integrationCredentials}}"
        httpMethod: POST
        responses:
          2\\d{2}:
            statusCode: "200"
          default:
            statusCode: "400"
            responseTemplates:
              "application/json": "json 400 response template"
      x-amazon-apigateway-request-validator: all
components:
  securitySchemes: {}
